var str = "abc_def_ghi_jkl_mn";
console.log("abc\ndefghi\\\n\'mn\'");
var str = "abc_def_ghi_jkl_mn";
str.split("_");
str.split("_",2);
str.concat("_opq");
str.substr(4,7);
str.substring(4,7);
str.slice(2);
str.slice(2,5);
str.slice(-2);
str.slice(2,-2);
str.bold();
str.link();
str.fontcolor("red");
str.fontsize(50);